## 개발(로컬) 환경 설정

db:
  datasource:
    url: jdbc:mysql://localhost:3306/fivelogs?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: fiveguy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

redis:
  host: localhost

custom:
  site:
    frontUrl: "http://localhost:3000"
    backUrl: "http://localhost:${server.port}"