custom:
  site:
    frontUrl: "https://www.fivelogs.site"
    backUrl: "https://api.fivelogs.site"

db:
  datasource:
    url: "${rds.url}"
    username: "${rds.username}"
    password: "${rds.password}"
    driver-class-name: com.mysql.cj.jdbc.Driver


