custom:
  site:
    name: "BLOG"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

db:
  datasource:
    url: jdbc:mysql://database-1.c5wcay8ss6dm.ap-northeast-2.rds.amazonaws.com:3306/fivelogs?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver